apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong-operator
    spec:
      containers:
      - name: operator
        image: upmcenterprises/kong-operator:0.0.0
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace